detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
  TooManyStatements:
    enabled: false
  TooManyConstants:
    max_constants: 7
  InstanceVariableAssumption:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - e
exclude_paths:
    - db/
    - vendor/bundle

directories:
  "app/jobs**":
    UtilityFunction:
      enabled: false

  # allow_calls:
  #   - 'event.data'